# Generated by Django 5.0.3 on 2024-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_audio_remove_book_author_wiki_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='text',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
