# Generated by Django 5.0.3 on 2024-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_chapter_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, editable=False),
        ),
    ]
