# Generated by Django 5.0.3 on 2024-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, unique=True, verbose_name='Inter login')),
                ('password', models.CharField(max_length=25, verbose_name='Inter password')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Inter name')),
                ('author', models.BooleanField(default=False, verbose_name='Can posts')),
                ('avatar', models.ImageField(null=True, upload_to='images/', verbose_name='Загрузите обложку книги')),
            ],
        ),
    ]
